var annotated_dup =
[
    [ "Atividade", "class_atividade.html", "class_atividade" ],
    [ "Avaliacao", "class_avaliacao.html", "class_avaliacao" ],
    [ "Codigo", "class_codigo.html", "class_codigo" ],
    [ "Conta", "class_conta.html", "class_conta" ],
    [ "Data", "class_data.html", "class_data" ],
    [ "Destino", "class_destino.html", "class_destino" ],
    [ "Dinheiro", "class_dinheiro.html", "class_dinheiro" ],
    [ "Duracao", "class_duracao.html", "class_duracao" ],
    [ "Horario", "class_horario.html", "class_horario" ],
    [ "Hospedagem", "class_hospedagem.html", "class_hospedagem" ],
    [ "Nome", "class_nome.html", "class_nome" ],
    [ "Senha", "class_senha.html", "class_senha" ],
    [ "TUAtividade", "class_t_u_atividade.html", "class_t_u_atividade" ],
    [ "TUAvaliacao", "class_t_u_avaliacao.html", "class_t_u_avaliacao" ],
    [ "TUCodigo", "class_t_u_codigo.html", "class_t_u_codigo" ],
    [ "TUConta", "class_t_u_conta.html", "class_t_u_conta" ],
    [ "TUData", "class_t_u_data.html", "class_t_u_data" ],
    [ "TUDestino", "class_t_u_destino.html", "class_t_u_destino" ],
    [ "TUDinheiro", "class_t_u_dinheiro.html", "class_t_u_dinheiro" ],
    [ "TUDuracao", "class_t_u_duracao.html", "class_t_u_duracao" ],
    [ "TUHorario", "class_t_u_horario.html", "class_t_u_horario" ],
    [ "TUHospedagem", "class_t_u_hospedagem.html", "class_t_u_hospedagem" ],
    [ "TUNome", "class_t_u_nome.html", "class_t_u_nome" ],
    [ "TUSenha", "class_t_u_senha.html", "class_t_u_senha" ],
    [ "TUViagem", "class_t_u_viagem.html", "class_t_u_viagem" ],
    [ "Viagem", "class_viagem.html", "class_viagem" ]
];